### ISSUE TITLE
error finding tslint when installed globally

### ISSUE THREAD

**Issue by thomasjshafer** [AtomLinter/linter-tslint#102]
Hey tslint,

Perhaps this is a nonissue but, I'm having issues using the recommended lint specs when `tslint` is only installed globally. The linter throws this error:
>
Error: Invalid "extends" configuration value - could not require "tslint:recommended". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.

See screenshot: 
![screenshot from 2016-07-07 14 11 29](https://cloud.githubusercontent.com/assets/135461/16669950/da62a59a-444c-11e6-928a-43c265844fac.png)

I did get it to work with a local tslint installation.

**Comment by lhecker** [comment]
@thomasjshafer The published version of this project uses tslint v3.10.2 which does not have the `extends` property yet. #105 should fix that.

**Comment by Arcanemagus** [comment]
Looks like @AtomLinter/linter-tslint hasn't published a release in a while, I'll push one out for you 😉.

**Comment by Arcanemagus** [comment]
v0.11.0 published updating `tslint` to v3.14.0.
