### ISSUE TITLE
Uncaught EvalError

### ISSUE THREAD

**Issue by jtmthf** [AtomLinter/linter-tslint#103]
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

Getting this error whenever I'm using linter-tslint

**Comment by Arcanemagus** [comment]
Closing as a duplicate of #104, as they provided full debugging information.

Also published an update that includes an update of `tslint` to v3.14.0, please try `linter-tslint` v0.11.0 and see if you are still having this issue.
