### ISSUE TITLE
Enable type-checking for rules that needs it

### ISSUE THREAD

**Issue by beckend** [AtomLinter/linter-tslint#109]
Getting a lot(or same) error repeatedly when using latest tslint.
It says on tslint gh:

> To enable rules that work with the type checker, a TypeScript program object must be passed to the linter
# https://github.com/palantir/tslint/issues/1445

**Comment by isiahmeadows** [comment]
This would also be nice. It shouldn't take much work to do it, considering that [TSLint has a few helper functions to make this very simple](https://github.com/palantir/tslint#type-checking).

**Comment by Arcanemagus** [comment]
@isiahmeadows I'd be happy to review a PR 😉.

**Comment by isiahmeadows** [comment]
I've been majorly backed up lately, or I probably would've already.

**Comment by zaggino** [comment]
Hi guys, tried to fix this with the helper mentioned above but I don't think it produces proper valid Program instance. I've already implemented type-checking in my https://github.com/zaggino/brackets-typescript repository but it's much more complex there because I also re-implemented whole TypeScript's Language Service.

My attempt diff makes `linter-tslint` fail deep inside `node_modules\typescript\lib\typescript.js`:
```
     );
   },

+  getProgram(Linter, configurationPath) {
+    let program;
+    try {
+      const tsconfigPath = path.resolve(path.dirname(configurationPath), 'tsconfig.json');
+      const isFile = fs.statSync(tsconfigPath).isFile();
+      if (isFile) {
+        program = Linter.createProgram('tsconfig.json', path.dirname(configurationPath));
+      }
+    } catch (err) {
+      // no-op
+    }
+    return program;
+  },
+
   provideLinter() {
     // eslint-disable-next-line import/no-dynamic-require
     tslintDef = require('loophole').allowUnsafeNewFunction(() => require(TSLINT_MODULE_NAME).Linter);
@@ -144,7 +158,7 @@ export default {
           const linter = new Linter({
             formatter: 'json',
             rulesDirectory,
-          });
+          }, this.getProgram(Linter, configurationPath));

           linter.lint(filePath, text, configuration);
           const lintResult = linter.getResult();
```

**Comment by newtrat** [comment]
@zaggino your solution works perfectly for me! I am hesitant to issue a pull request since the fix was your idea, and apparently it doesn't work for everyone, but I can confirm that it does work in principle. Have you been able to find a solution that works for you?

**Comment by newtrat** [comment]
Ah, and as mentioned in #93 @beckend has also solved this issue in his own plugin at https://github.com/beckend/linter-tslint2

**Comment by zaggino** [comment]
feel free to use the code however you wish @newtrat , I didn't work for me so I've switched back to Brackets for my TypeScript projects
