### ISSUE TITLE
TSLint 4.0 support

### ISSUE THREAD

**Issue by jesperronn** [AtomLinter/linter-tslint#123]
Hi, as a user of this plugin I saw in `package.json` that it currently uses tslint 3.15. 

How can I update it to use tslint 4.0?

Will it work out of the box? Could you perhaps make a release with tslint 4.0?

Ps. I see that other projects are currently migrating to tslint. Two examples: [Codelyzer](https://github.com/mgechev/codelyzer/pull/158) and [gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint/commit/38da472fa24267ba7f227c59cf4372b4624d69be)

**Comment by scttcper** [comment]
angular-cli just updated https://github.com/angular/angular-cli/pull/3304

**Comment by GabiGrin** [comment]
and using local tslint version doesn't work - https://github.com/AtomLinter/linter-tslint/blob/master/lib/main.js#L63 :(

**Comment by scttcper** [comment]
https://github.com/AtomLinter/linter-tslint/pull/124

**Comment by Arcanemagus** [comment]
Fixed in #124, will be published as soon as #126 gets merged.
