### ISSUE TITLE
How to work with Mocha, Jasmine, etc.

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-tslint#128]
How do I configure this plugin to ignore errors for Mocha, Jasmine, etc

![image](https://cloud.githubusercontent.com/assets/183153/21209526/ae47a1da-c229-11e6-9488-fcb9fd8d8c2f.png)

**Comment by swinc** [comment]
`import {} from 'mocha'` worked for me.

**Comment by mikeerickson** [comment]
@swinc thanks for the tip, however, still have the same issue.

**Comment by mikeerickson** [comment]
@swinc curiously enough, I changed it to 

```
import {} from 'jasmine"
```

Seeing as jasmine is the test framework used by `angular-cli` which created this test, this makes good sense to me :-)

**Comment by Arcanemagus** [comment]
Just a note, this has _nothing_ to do with this package, and is solely a configuration issue for `tslint`.
