### ISSUE TITLE
Highlighting in the editor messing up with line numbers

### ISSUE THREAD

**Issue by sobit** [AtomLinter/linter-tslint#13]
Using latest versions of Atom and packages.

Here a warning is produced:
![screenshot 2015-05-14 16 58 57](https://cloud.githubusercontent.com/assets/1245542/7634361/babfec80-fa5a-11e4-9022-81c66ec38870.png)

But when you place a cursor on it, that's the message you get:
![screenshot 2015-05-14 16 59 08](https://cloud.githubusercontent.com/assets/1245542/7634360/babc9b52-fa5a-11e4-8e0e-67e4d8099df5.png)

Which apparently is related to the next line in the editor (19).

Running tslint manually though shows the information properly:
```
src/index.ts[19, 11]: expected variable-declaration: 'stripe' to have a typedef
```

So I guess it's a problem with either linter or linter-tslint. Would appreciate any help.

**Comment by trkoch** [comment]
I can confirm this behavior (Atom 0.200.0, Mac OS X, integrated linter-tslint 0.2.1). Any hints?

**Comment by trkoch** [comment]
I suspect substracting one line (or column) in `processMessage` (found in file linter-tslint.coffee) should be removed.

**Comment by PLEEROCK** [comment]
+1

**Comment by tomitrescak** [comment]
Yes, still the same at latest version.

**Comment by carlo** [comment]
+1

**Comment by carlo** [comment]
**Update:** after clearing the "Tslint Executable Path" in the linter-tslint settings (making it use its packaged tslint), the line and columns are marked correctly.

Atom 0.211, linter-tslint 0.2.2, OS X 10.10.3.

**Comment by adidahiya** [comment]
TS language services fixed the way they report line and col numbers (I think in TS v1.4?) and that change propagated to tslint. So you no longer have to subtract 1 from the reported line and column position. I opened a PR with the fix.
