### ISSUE TITLE
globals defined in tslint.json file are ignored

### ISSUE THREAD

**Issue by svassr** [AtomLinter/linter-tslint#130]
In spec files I get a lot of messages like `Cannot find name 'describe'`. I tried to define globals array in the tslint.json file at the root of my project but it has no effect.

**Comment by swinc** [comment]
The solution some of us have used for this is to `import {} from 'mocha';` (or jasmine or whichever testing library you are using) in one of those spec files.

**Comment by Xapphire13** [comment]
TSLint doesn't support globals like ESLint does. This change would need to be made to TSLint itself
