### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-tslint#15]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by Arcanemagus** [comment]
@park9140 @kevinsawicki  Do either of you want to update this linter to the new API? I can take a stab at it if instead if you would like, but I don't actually use this linter myself.

**Comment by kevinsawicki** [comment]
> Do either of you want to update this linter to the new API?

I don't use this linter myself either, I previously just upgraded it to the Atom 1.0 APIs so it wouldn't break.

**Comment by Arcanemagus** [comment]
Ah, just tagged the last two people I saw committing/merging stuff :wink:.

**Comment by Arcanemagus** [comment]
I'll dig into this tomorrow if @park9140 hasn't responded by then, don't want people stuck on `linter@1.2.4` forever just because their favorite linter hasn't been updated.

**Comment by park9140** [comment]
@Arcanemagus, I don't have time to work on this today or tomorrow.  I will probably get annoyed by it being broken by the end of the week though if you don't have time for it.

**Comment by tomitrescak** [comment]
If you would update those API calls, would be very much appreciated! Can't really use new typescript because of this. Thanks!

**Comment by markvandenbrink** [comment]
:+1: Would be great if the TypeScript linter starts working again. Thanks for all the hard work!

**Comment by markvandenbrink** [comment]
Any news on the required changes to fix tslint? Is a complete rewrite necessary? I really miss the TypeScript linter in Atom :-( Let me know if any help is appreciated, though I am not yet familiar with the linter API. I'm curious about the required work...

**Comment by Arcanemagus** [comment]
@markvandenbrink essentially this does involve a re-write. You _can_ create a wrapper around the old way of doing things, but often it's just as simple to write it from scratch. I haven't had time to deal with this so I'm sure @park9140 (and everyone using this) would love it if you would take a stab at it :wink:.

**Comment by tomitrescak** [comment]
Hello, I know that this is open-source project which you guys most probably do in your spare time (I have several of my own), but leaving, 13.000 people hanging like this is not cool :/ If it would be an enhancement I can completely understand, but maintenance ... It's been a month now since this package is out of order. Is it really that difficult to remap to new API with your previous experience with linter?

**Comment by AsaAyers** [comment]
I don't write code for projects I don't use. It has been 70 days since 1.0
launched, someone who depends on this linter can step up and maintain it.

I'm not aware of any other linter with this problem. They have all either
been updated or even the users have abandoned them.

**Comment by park9140** [comment]
I threw together a fix.  Report issues on #21 if they seem related otherwise create new issues.
