### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by kyleholliday** [AtomLinter/linter-tslint#159]
Uninstalling “linter-tslint” failed.

`Failed to delete linter-tslint: EACCES: permission denied, unlink '/Users/kyleholliday/.atom/packages/linter-tslint/.editorconfig'`

**Comment by Xapphire13** [comment]
Have you tried installing after restarting your machine. Something may have a file handle open on that file.

**Comment by Arcanemagus** [comment]
If you accidentally did `sudo apm install linter-tslint` the permissions will be screwed up on the folder, that's the most common case of this that I see.

**Comment by Xapphire13** [comment]
@kyleholliday Did the suggestions solve your issue?

**Comment by kyleholliday** [comment]
@Xapphire13 Restarting after force deleting it solved the issue. Thanks!
