### ISSUE TITLE
Warning is placed to the line above right place

### ISSUE THREAD

**Issue by richardsabow** [AtomLinter/linter-tslint#16]
When i use the new `namespace` keyword instead of `module`, the warnings aren't placed to the right line.
See in the example: the variable name `news_List` in line 5. is invalid, it should be `newsList`. The warning (`variable name must be in camelcase or uppercase`) is placed to line 4.
![screen shot 2015-06-16 at 18 56 38](https://cloud.githubusercontent.com/assets/9129389/8188982/78cbb110-1459-11e5-9112-ddf5639e3262.png)

If i use `module` instead of `namespace` everything works fine.

**Comment by richardsabow** [comment]
Sorry, i think it's the same issue as https://github.com/AtomLinter/linter-tslint/issues/13

**Comment by park9140** [comment]
:wrench: by @adidahiya
