### ISSUE TITLE
No longer working on Arch

### ISSUE THREAD

**Issue by loxiw** [AtomLinter/linter-tslint#162]
I noticed this is happening since v1.0.0 (in fact I'm actually working without problems with v0.15.0).

Linter does nothing at all, and whenever I work with a .ts file I get this constantly prompted
![image](https://cloud.githubusercontent.com/assets/4063362/25422203/5c723c86-2a60-11e7-9420-f561c54320b0.png)

This is what the inspector says
![image](https://cloud.githubusercontent.com/assets/4063362/25422236/88bf7b64-2a60-11e7-86bb-a82d0668873b.png)

**Comment by Arcanemagus** [comment]
What version of Atom are you on?

**Comment by loxiw** [comment]
1.16.0

**Comment by loxiw** [comment]
This is weird, since today (Arch updates?) 0.15.0 no longer works and 1.3.0 started working, but working with a strange behaviour, everything that was marked with a severity of  Warning before is now an Error I don't think

**Comment by Xapphire13** [comment]
Odd. Let's keep this open a few more days to see if it happens again. If it does, could you try the TSLint CLI to see if that has issues (version `5.1.0`)?
