### ISSUE TITLE
Unexpected string in JSON at position 1263

### ISSUE THREAD

**Issue by granteagon** [AtomLinter/linter-tslint#174]
Getting the following error in the latest version 1.5.0:

```
events.js:106 Unexpected string in JSON at position 1263 SyntaxError: Unexpected string in JSON at position 1263
    at Object.parse (native)
    at Function.loadConfigurationFromPath (C:\Projects\Web Applications\swagger2ts\node_modules\tslint\lib\configuration.js:165:38)
    at file:///C:/Users/geagon/.atom/packages/linter-tslint/lib/worker.js:142:34
    at next (<anonymous>)
    at step (file:///C:/Users/geagon/.atom/packages/linter-tslint/lib/worker.js:204:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)(anonymous function) @ <embedded>:70040(anonymous function) @ <embedded>:70114module.exports.Emitter.simpleDispatch @ <embedded>:62396module.exports.Emitter.emit @ <embedded>:62512(anonymous function) @ <embedded>:70066emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
linter-registry.js:137 [Linter] Error running TSLint Error: Unexpected string in JSON at position 1263(…)(anonymous function) @ linter-registry.js:137_tickCallback @ internal/process/next_tick.js:103
```

Other dependencies:
    "ts-loader": "^2.0.1",
    "tslint": "^5.3.2",
    "tslint-loader": "^3.5.2",
    "typescript": "^2.3.3",

**Comment by Xapphire13** [comment]
Does the issue happen when you use the TSLint CLI?

**Comment by granteagon** [comment]
You nailed it.  Bad JSON.  Thanks.

**Comment by unsama** [comment]
build.js:1 SyntaxError: {
  "name": "sp-main",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "nodemon ./bin/www",
    "watchify": "watchify -vd -e src/Pages/Setting/main.js -o public/Modules/Setting/build.js",
    "watchifypurchase": "watchify -vd -e src/Pages/Purchase/main.js -o public/Modules/Purchase/build.js",
    "dev": "npm-run-all --parallel watchify start",
    "build": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Setting/build.css ] -e src/Pages/Setting/main.js | uglifyjs -c warnings=false -m > public/Modules/Setting/build.js",
    "build_accounting": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Accounting/build.css ] -e src/Pages/Accounting/main.js | uglifyjs -c warnings=false -m > public/Modules/Accounting/build.js",
    "build_attendance": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Attendance/build.css ] -e src/Pages/Attendance/main.js | uglifyjs -c warnings=false -m > public/Modules/Attendance/build.js",
    "build_calendar": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Calendar/build.css ] -e src/Pages/Calendar/main.js | uglifyjs -c warnings=false -m > public/Modules/Calendar/build.js",
    "build_dashboards": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Dashboards/build.css ] -e src/Pages/Dashboards/main.js | uglifyjs -c warnings=false -m > public/Modules/Dashboards/build.js",
    "build_discuess": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Discuess/build.css ] -e src/Pages/Discuess/main.js | uglifyjs -c warnings=false -m > public/Modules/Discuess/build.js",
    "build_employees": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Employees/build.css ] -e src/Pages/Employees/main.js | uglifyjs -c warnings=false -m > public/Modules/Employees/build.js",
    "build_expenses": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Expenses/build.css ] -e src/Pages/Expenses/main.js | uglifyjs -c warnings=false -m > public/Modules/Expenses/build.js",
    "build_inventory": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Inventory/build.css ] -e src/Pages/Inventory/main.js | uglifyjs -c warnings=false -m > public/Modules/Inventory/build.js",
    "build_leaves": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Leaves/build.css ] -e src/Pages/Leaves/main.js | uglifyjs -c warnings=false -m > public/Modules/Leaves/build.js",
    "build_maintenance": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Maintenance/build.css ] -e src/Pages/Maintenance/main.js | uglifyjs -c warnings=false -m > public/Modules/Maintenance/build.js",
    "build_manufacturing": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Manufacturing/build.css ] -e src/Pages/Manufacturing/main.js | uglifyjs -c warnings=false -m > public/Modules/Manufacturing/build.js",
    "build_notes": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Notes/build.css ] -e src/Pages/Notes/main.js | uglifyjs -c warnings=false -m > public/Modules/Notes/build.js",
    "build_pointofsale": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Pointofsale/build.css ] -e src/Pages/Pointofsale/main.js | uglifyjs -c warnings=false -m > public/Modules/Pointofsale/build.js",
    "build_projects": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Projects/build.css ] -e src/Pages/Projects/main.js | uglifyjs -c warnings=false -m > public/Modules/Projects/build.js",
    "build_purchase": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Purchase/build.css ] -e src/Pages/Purchase/main.js | uglifyjs -c warnings=false -m > public/Modules/Purchase/build.js",
    "build_recruitment": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Recruitment/build.css ] -e src/Pages/Recruitment/main.js | uglifyjs -c warnings=false -m > public/Modules/Recruitment/build.js",
    "build_repairs": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Repairs/build.css ] -e src/Pages/Repairs/main.js | uglifyjs -c warnings=false -m > public/Modules/Repairs/build.js",
    "build_sales": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Sales/build.css ] -e src/Pages/Sales/main.js | uglifyjs -c warnings=false -m > public/Modules/Sales/build.js",
    "build_testing": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Testing/build.css ] -e src/Pages/Testing/main.js | uglifyjs -c warnings=false -m > public/Modules/Testing/build.js",
    "build_timesheet": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Timesheet/build.css ] -e src/Pages/Timesheet/main.js | uglifyjs -c warnings=false -m > public/Modules/Timesheet/build.js"
    "build_contacts": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o public/Modules/Timesheet/build.css ] -e src/Pages/Timesheet/main.js | uglifyjs -c warnings=false -m > public/Modules/Timesheet/build.js"
  },
  "browserify": {
    "transform": [
      "babelify",
      "vueify"
    ]
  },
  "browser": {
    "vue": "vue/dist/vue.common.js"
  },
  "dependencies": {
    "babel-core": "^6.25.0",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "~1.15.2",
    "chart.js": "^2.6.0",
    "connect-flash": "^0.1.1",
    "connect-history-api-fallback": "^1.3.0",
    "cookie-parser": "~1.4.3",
    "csurf": "^1.9.0",
    "debug": "~2.2.0",
    "envify": "^4.1.0",
    "express": "~4.14.0",
    "express-session": "^1.15.0",
    "express-validator": "^3.2.1",
    "jade": "~1.11.0",
    "lodash": "^4.17.4",
    "mongoose": "^4.11.1",
    "morgan": "~1.7.0",
    "multer": "^1.3.0",
    "mysql": "^2.13.0",
    "nodemailer": "^3.0.2",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "plotly": "^1.0.6",
    "randomstring": "^1.1.5",
    "serve-favicon": "~2.3.0",
    "simple-ssh": "^0.9.0",
    "uglify-js": "^2.8.29",
    "vee-validate": "^2.0.0-rc.7",
    "vue": "^2.3.4",
    "vue-resource": "^1.3.4",
    "vue-router": "^2.7.0",
    "vue-sortable": "^0.1.3",
    "vueify": "^9.4.1"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-runtime": "^6.0.0",
    "babelify": "^7.3.0",
    "browserify": "^14.1.0",
    "browserify-hmr": "^0.3.1",
    "browserify-middleware": "^7.1.0",
    "cross-env": "^4.0.0",
    "nodemon": "^1.11.0",
    "npm-run-all": "^2.3.0",
    "uglify-js": "^2.5.0",
    "vueify": "^9.4.0",
    "watchify": "^3.4.0"
  }
}
 : Unexpected string in JSON at position 5534




I dont know whats the error, can you help me out this?

**Comment by granteagon** [comment]
![aaaaaa](https://user-images.githubusercontent.com/133823/29409242-6005bb90-8319-11e7-9b91-9155d3c535d4.png)

**Comment by unsama** [comment]
granteagon  thanks Bro you save my life  :D

**Comment by unsama** [comment]
192.168.25.104:8069/web/image?model=res.partner&id=50&field=image_medium&unique=20170324135646:1 GET http://192.168.25.104:8069/web/image?model=res.partner&id=50&field=image_medium&unique=20170324135646 net::ERR_CONNECTION_TIMED_OUT


please help me  out Thanks in Advance

**Comment by Arcanemagus** [comment]
Locking this conversation, @unsama your problems aren't related to this package but seem to be general issues with your web development setup (in your last case, whatever server you are running isn't accepting connections). You should look for a place to get general help with web development with things like that 😉.
