### ISSUE TITLE
"The linter binary 'tslint' cannot be found."

### ISSUE THREAD

**Issue by teddybradford** [AtomLinter/linter-tslint#18]
I keep getting the error: `The linter binary 'tslint' cannot be found. Linting has been halted. Please install the linter binary or disable the linter plugin depending on it. Make sure to reload Atom to detect changes`

I have confirmed that the `tslint` binary is in the `linter-tslint/node_modules/tslint/bin/` directory, and I even tried installing tslint globally and setting the path in my Atom config accordingly to no avail. I'm running OS X Yosemite.

Any idea what I'm missing here?

**Comment by tomitrescak** [comment]
Same here +1 
Linting continues afterwards, but I keep receiving these errors quite often.

**Comment by steve8708** [comment]
Same problem here too, any tips tremendously appreciated :)

**Comment by adidahiya** [comment]
This happened to me with tslint and other linters like scss-lint. I got it to work by launching Atom from a terminal (`$ atom path/to/project/folder/`) rather than the Applications folder.

**Comment by park9140** [comment]
@teddybradford , @steve8708, @adidahiya  I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.  Report issues on #21

**Comment by steve8708** [comment]
Works for me now, thanks @park9140 !

**Comment by tomitrescak** [comment]
Hooray! Thanks! Works :+1:
