### ISSUE TITLE
Linting HTML/Vue files

### ISSUE THREAD

**Issue by b-zee** [AtomLinter/linter-tslint#187]
Similar to [`AtomLinter/linter-eslint`#576](https://github.com/AtomLinter/linter-eslint/issues/576).

`linter-eslint` has an option to enable linting HTML files, which enables linting Vue files by using [`BenoitZugmeyer/eslint-plugin-html`](https://github.com/BenoitZugmeyer/eslint-plugin-html). I am wondering about a similar solution for `linter-tslint`.

**Comment by Xapphire13** [comment]
The plugin you linked to is for ESLint itself, not the atom plugin. TSLint would need similar support built in for AtomLinter/linter-tslint to leverage it. There is an [open bug](https://github.com/palantir/tslint/issues/2099) on TSLint requesting this feature.

Closing as external for now. Feel free to reopen when TSLint supports this.

**Comment by entepe85** [comment]
This should be reopened now, because TSLint itself now supports linting of Vue single file components whereas linter-tslint does not.

**Comment by entepe85** [comment]
Any progress on this? I'd love to be able to lint my TS-based Vue Single File Components in Atom itself (as opposed to the CLI).
