### ISSUE TITLE
"Try using local tslint package" setting doesn't seem to work

### ISSUE THREAD

**Issue by bronson** [AtomLinter/linter-tslint#199]
I have tslint 2.5.2 installed in my project (in package.json and node_modules).  When I invoke tslint on the command line, it lints my project just fine.

However, when I try linting inside Atom, I get a few errors that were fixed in the typescript 2.5 series.  It seems pretty likely that linter-tslint is using its own older version of tslint.

The "Try using the local tslint package (if exist)" checkbox is checked.  Any idea why it's still not using my local tslint?

**Comment by bronson** [comment]
Maybe we also need a "try using the local typescript" checkbox?

**Comment by bronson** [comment]
I disabled linter-tslint and still get the errors.  It appears the culprit is ide-typescript.  Sorry, I'll open an issue over there.

**Comment by Xapphire13** [comment]
Thanks for the investigation!

**Comment by bronson** [comment]
FWIW, this was the issue: https://github.com/atom/ide-typescript/issues/22

Not an easy one to fix!
