### ISSUE TITLE
Linter.createProgram() invoked with incorrect config path

### ISSUE THREAD

**Issue by smhxx** [AtomLinter/linter-tslint#201]
Hi again! 😛

I was digging around trying to investigate some strange behavior I was seeing related to the "Enable semantic rules" setting, and I think I've discovered the source of the inconsistent behavior between `linter-tslint` with type-checking enabled, and the command-line `tslint --project --type-check`. Looking at the other open issues, I strongly suspect that this bug is the root cause of #192 and/or #200.

The [`createProgram()` method of `tslint`](https://github.com/palantir/tslint/blob/d45d227f7487f037e85a7f29c335e6dd3b19a6d6/src/linter.ts#L56) expects the *full path* to the tsconfig file to be passed as the first argument, but currently `linter-tslint` is passing **only** the basename of the file, which results in `tslint` being unable to properly resolve the project's compiler configuration. Changing this to pass the full path to the tsconfig file, rather than just 'tsconfig.json' causes the displayed output to be consistent with what is returned by `tslint --project`.

It's a super, *super* easy one-line fix, but should in theory fix a lot of the problems people have been seeing with the type-checking/"semantic rules" feature.

**Comment by smhxx** [comment]
So, I'm a bit conflicted now... while this is [definitely a bugfix](https://github.com/Microsoft/TypeScript/blob/27f9cdb1aec60c60ed2af52c2e4f470f6ee7dcbe/src/compiler/commandLineParser.ts#L882), I'm no longer sure that `linter-tslint` is even to blame for the oddities I was seeing earlier. In fact, I think it may actually be a problem in `javascript-typescript-langserver`, completely unrelated to the linter. Oh, well. Maybe this will fix one of those other two issues, or prevent problems in the future. xD

**Comment by Arcanemagus** [comment]
Should this be marked as fixed? Was it ever even a bug with `linter-tslint`?

**Comment by smhxx** [comment]
Yes, it was definitely a bug, I'm just not sure if it was the *entire* cause of the oddities that caused me to go looking for it. Fixing it definitely improved the situation, although now I think I may be running into some peculiarities with `javascript-typescript-langserver`... that's easy enough to work around, though, so I think it's all good for now. Any involvement from `linter-tslint` should be fixed.
