### ISSUE TITLE
How to specify the tslint path?

### ISSUE THREAD

**Issue by eyaleizenberg** [AtomLinter/linter-tslint#203]
In my project, the tslint path is nested under a different node module than tslint.

How can I specify it?

Thanks.

**Comment by Xapphire13** [comment]
Can you give an example?

**Comment by eyaleizenberg** [comment]
@Xapphire13 The path of the tslint file in my project is `node_modules/yoshi/plugins/node_modules/tslint/bin`

This is easily configurable in webstorm so probably a good idea to allow it here as well, don't you think? 😄

**Comment by Xapphire13** [comment]
I guess my first question is why not `npm install` the particular version of tslint you wish to use directly to your project? Or `npm dedupe` to flatten the dependency tree?
