### ISSUE TITLE
Specify tsconfig.json configuration file

### ISSUE THREAD

**Issue by PierreGUI** [AtomLinter/linter-tslint#205]
Hi there,
I can't figure how to pass the path to typescript configuration file.
The linter atom plugin now notifies me about bunch of errors about relative imports not being found and `assign` function not existing in `ObjectConstructor` type.

Of course, these won't show in my terminal when using tslint CLI, since proper config is set in my tsconfig file (eg: with `baseUrl` and `"lib": ["es2015"]`).
So, am I missing something?

Thanks!

**Comment by Xapphire13** [comment]
Judging by the error you mention, it sounds like your warning are coming from [atom-typescript](https://github.com/TypeStrong/atom-typescript).

This package only reports lint issues, not syntax/language issues. And only uses `tsconfig.json` when semantic rules are enabled (it assumes the file will be a sibling of `tslint.json`).

The `atom-typescript` package however perform a `findUp()` operation for the config file based on the path of the current file.

**Comment by smhxx** [comment]
Sounds like sourcegraph/javascript-typescript-langserver#351, maybe? I've encountered similar module resolution errors from `atom-typescript` in the past. As @Xapphire13 said, this sounds like it's probably external and is actually coming from `atom-typescript`, not the linter. Double-check the "provider" column of the errors you're seeing listed; if the provider is "tslint," then it's likely an issue with `tslint` or `linter-tslint`. If the provider is just "ts" (which it sounds like it probably is) then it's coming from the language support package or one of its dependencies.

**Comment by PierreGUI** [comment]
You guys are right. Hard to tell which error comes from where, but indeed I could have looked up a little closer.

Now, about specifying the path to a config file to the plugin, I have discussed it and it seems there's no easy solution out there. We would need Atom to support per-project configuration.
Thanks for your help!
