### ISSUE TITLE
LinterTslint.Linter is deprecated.

### ISSUE THREAD

**Issue by carlo** [AtomLinter/linter-tslint#21]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterTslint.Linter (/Users/czottmann/Settings/Atom/packages/linter/lib/linter.coffee:60:4)
new LinterTslint (/Users/czottmann/Settings/Atom/packages/linter-tslint/lib/linter-tslint.coffee:26:4)
Object.lint (/Users/czottmann/Settings/Atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/czottmann/Settings/Atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/czottmann/Settings/Atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/czottmann/Settings/Atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by jtrinklein** [comment]
Also seeing this issue.

**Comment by trodi** [comment]
:+1:

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/AtomLinter/linter-tslint/issues/15.

**Comment by park9140** [comment]
@jtrinklein, @carlo, @trodi, I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.

**Comment by trodi** [comment]
@park9140 - initial install and toying around runs as expected (running rules based on my tsconfig). I'll continue to look out for any issues. Thanks for publishing this!

**Comment by park9140** [comment]
@trodi, not sure if the performance will be a problem, I left it with lintOnFly true so it should lint continuously still, however, the linter runs serially in the code rather than in a secondary process.  There might be a performance problem.
