### ISSUE TITLE
fix errors on save doesn't work for SOME rules

### ISSUE THREAD

**Issue by carsonpowers** [AtomLinter/linter-tslint#214]
I have "Fix errors on save" selected and it's working for SOME of my rules, but not others:

[Video of the issue](https://sendvid.com/cmf7ykkc)

As you can see "var" changes to "let" and it adds a semi-colon (as per my tslint rules) but it fails to change my quotes! It also fails to remove white-space automatically on save.

Anyone have any ideas? Greatly appreciated!

**Comment by Arcanemagus** [comment]
Does `tslint` itself fix those issues? If it's doing _anything_ then it's likely out of the control of what we have here and on the `tslint` side.

**Comment by carsonpowers** [comment]
If I disable "linter-tslint" in my packages (in Atom) it stops fixing those issues, so yes I assume that tslint is fixing these issues.

Is there anyway to debug ts-linter to see where/if the error is occurring?

Thanks for the assistance, Arcanemagus

**Comment by Arcanemagus** [comment]
It looks like [`quotemark`](https://palantir.github.io/tslint/rules/quotemark/) supposedly has a fixer. Does it work when you request a fix from the CLI?

**Comment by carsonpowers** [comment]
GOT IT!

First of all, thank you Arcanemagus, I would not have been able to figure this out without your suggest to run it in CLI.

When ran tslint (filename.ts) it gave me the error that I have several old, deprecated codelyzer rules in my tslint.json file.

Upon inspecting my package.json file I noticed that my codelyzer package was VERY old:
>     "codelyzer": "~2.0.1",

 After updating to the newest version of codelyzer(4.0.2) it asked for me to update tslint, which was also working also an old version:
>     "tslint": "~4.0.0",

After updating to the newest version of tslint (5.8.0) it immediately began working.

**Comment by Arcanemagus** [comment]
Marking this as closed then, glad you got it figured out 😉.
