### ISSUE TITLE
Auto fix deletes trailing-whitespace in docs comments

### ISSUE THREAD

**Issue by justerest** [AtomLinter/linter-tslint#215]
Trailing whitespaces doesn't keeps if `fix errors on save` is on and tslint.json include
```json
"no-trailing-whitespace": [true, "ignore-comments"]
// or
"no-trailing-whitespace": [true, "ignore-jsdoc"]
```

**Comment by Arcanemagus** [comment]
You'll need to file this on [`tslint`](https://github.com/palantir/tslint), this is just a wrapper around that.
