### ISSUE TITLE
Typescript quit unexpectedly

### ISSUE THREAD

**Issue by kachkaev** [AtomLinter/linter-tslint#218]
Hi guys,

Just reporting that I'm seeing this error from time to time:

```
Typescript quit unexpectedly

Last output from tsserver:
v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x129567843a7
 ```

![screen shot 2018-02-07 at 13 07 52](https://user-images.githubusercontent.com/608862/35918031-3e3adeaa-0c08-11e8-8626-52cc762e15dc.png)

Once it has occurred, the only thing left to do is to restart Atom, which is a bit distracting. Here are my setup details:

* atom 1.23.3 on macOS High Sierra
* `linter-tslint` atom plugin 1.9.0
* `tslint` node package 5.9.1 (locally installed with yarn)

I'm not sure how to help because the error is pretty cryptic, but will be happy to run a few experiments to give you more stuff to investigate.

---

One more error kind:

```
Typescript quit unexpectedly
Last output from tsserver:
node::Abort() [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::compiler::Node::Uses::empty() const [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: 0x2e5ed6c043a7
 9: 0x2e5ed7529dc4
10: 0x2e5ed72c2ae4
11: 0x2e5ed75620dc
12: 0x2e5ed74ba4ff
13: 0x2e5ed6fea605
14: 0x2e5ed74c641a
```

![screen shot 2018-02-07 at 13 20 46](https://user-images.githubusercontent.com/608862/35918453-ce43cb3c-0c09-11e8-9a6c-1a8c291029ae.png)

**Comment by Xapphire13** [comment]
This project doesn't use TSServer, I think your issue may be originating from [atom-typescript](https://github.com/TypeStrong/atom-typescript). Could you paste the output from the console in the developer tools? (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>)

**Comment by kachkaev** [comment]
Thanks for your response @Xapphire13! Will share the console output when I hit the error next time.
