### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by manishtpatel** [AtomLinter/linter-tslint#22]
I have been trying to get this working in windows 7. Not working for me. Nothing in debugger except 2 depreciation messages related to linter.

I got latest linter and tslint installed. tslint works from command line just fine. do i need anything else? linter is fine as well as it works for atom-typescript.

Tried different config file, but tslint is already in my path so following config doesn't make any difference.

  "linter-tslint":
    tslintExecutablePath: "C:/Users/user1/AppData/Roaming/npm/node_modules/tslint/bin/tslint"

**Comment by AllisonLamm** [comment]
Likely caused by Issue #21

**Comment by Arcanemagus** [comment]
Actually caused by https://github.com/AtomLinter/linter-tslint/issues/15, especially now that the deprecated API has been completely removed.

**Comment by park9140** [comment]
@manishtpatel, @AllisonLamm I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.  Report issues on #21
