### ISSUE TITLE
No longer works on linter 0.3.0

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/linter-tslint#23]
The linter no longer works. Linter team mentions package deprecation in atom-community/linter#796

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/AtomLinter/linter-tslint/issues/15.

**Comment by park9140** [comment]
@tomitrescak, @Arcanemagus.  I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.
