### ISSUE TITLE
does not respect compiler options set it files that tsconfig extends

### ISSUE THREAD

**Issue by radfahrer** [AtomLinter/linter-tslint#231]
our tsconfig.json file is very simple:
```
    {
	    "extends": "./tsconfig.base.json",
	     "compilerOptions": {
                 "allowJs": true,
		"checkJs": true
	    }
    }
```
and then other options are defined in tsconfig.base.json

this seems to work from the command line, but linter-tslint isn't picking up the options in .tsconfig.base.json

Specifically we are using decorators and the option "experimentalDecorators": true, isn't working.

**Comment by aminya** [comment]
Fixed in #396. This is a bug in tslint itself, but I fixed it using some workarounds.
