### ISSUE TITLE
Custom ruleset

### ISSUE THREAD

**Issue by n2westman** [AtomLinter/linter-tslint#24]
How can I specify which ruleset to use?

**Comment by park9140** [comment]
@n2westman, you can create a tslint.json in your project directory which will automatically be used when a file under that directory is linted.  

Please close if this fixes your issue. 

Also linter should work again (though may have issues)

**Comment by n2westman** [comment]
Does that mean it just recurses up the file tree (starting at the typescript file) looking for a tslint.json? Or it just searches the base directory of whatever is open in atom?

**Comment by park9140** [comment]
This actually just calls to the same logic as running `tslint /projectDir/module/directory/file.ts` on your command line.

For example:
You are editing `/projectDir/module/directory/file.ts`

you have a `tslint.json` file in `/projectDir/tslint.json`

The linter will search up from the file.ts directory till it finds `/projectDir/tslint.json`

if you put a `tslint.json` file in `/projectDir/module/tslint.json` it would find that first and take it.

**Comment by n2westman** [comment]
That's great, thanks!

On Thu, Sep 3, 2015 at 3:42 PM, Jonathan Park <notifications@github.com>
wrote:

> This actually just calls to the same logic as running tslint
> /projectDir/module/directory/file.ts on your command line.
>
> For example:
> You are editing /projectDir/module/directory/file.ts
>
> you have a tslint.json file in /projectDir/tslint.json
>
> The linter will search up from the file.ts directory till it finds
> /projectDir/tslint.json
>
> if you put a tslint.json file in /projectDir/module/tslint.json it would
> find that first and take it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/linter-tslint/issues/24#issuecomment-137593616>
> .
>



-- 
Nick Westman
UCLA Computer Science & Engineering '15
UCLA Engineering Ambassador
nickolas@upe.seas.ucla.edu
