### ISSUE TITLE
"Linter.lintsOnChange must be a boolean"

### ISSUE THREAD

**Issue by roddypratt** [AtomLinter/linter-tslint#247]
Using linter 2.3.0, linter-tslint 1.10.3, Atom 1.34.0 x64  on Windows 10.

I've just updated packages (I think both linter and linter-tslint received updates) and now I get this error at startup.
 
![image](https://user-images.githubusercontent.com/1199520/51462282-1cdbb880-1d58-11e9-954d-2202079c6206.png)

**Comment by yarozar** [comment]
I have same issue

**Comment by roddypratt** [comment]
The `lintOnFly `flag has be superseded in V2 with `lintsOnChange`. See https://steelbrain.me/linter/guides/upgrading-to-standard-linter-v2.html

**Comment by Arcanemagus** [comment]
Wow, how did I miss that here as well?! 🤦‍♂️

**Comment by roddypratt** [comment]
Thanks for the prompt fix ;)
