### ISSUE TITLE
config is ignored

### ISSUE THREAD

**Issue by yoorek** [AtomLinter/linter-tslint#26]
here is part of my config.cson:

  "linter-tslint":
    "quotemark": [
      true
      "single"
    ]
  

still, get lots of error for "double quotemarks"

**Comment by park9140** [comment]
@yoorek, you will need to create a tslint.json file in your project folder in order to apply a config.  Like the sample here https://github.com/palantir/tslint/blob/master/docs/sample.tslint.json
