### ISSUE TITLE
Add a rulesDirectory property

### ISSUE THREAD

**Issue by buzinas** [AtomLinter/linter-tslint#36]
Today, we call the TSLint's Linter construction as follows:

```javascript
linter = new Linter(filePath, text, {
  formatter: 'json',
  configuration: configuration
});
```

But there is also a `rulesDirectory` property for custom rules created by users.

Could you please add a parameter to the plugin, so we can set this parameter?

**Comment by Arcanemagus** [comment]
Do you want to submit a PR for this? I don't believe this package has an active maintainer and I don't use it myself...

**Comment by buzinas** [comment]
I would like to submit it, but unfortunately I have never coded with CoffeeScript, and never used Atom API either.

Can you give me some advices/orientation?

**Comment by Arcanemagus** [comment]
I'm guessing you will want a configuration option to specify the rules directory, an example can be found for specifying options [here](https://github.com/AtomLinter/linter-php/blob/master/lib/main.coffee#L5-L9), with how to properly `observe()` the settings [here](https://github.com/AtomLinter/linter-php/blob/master/lib/main.coffee#L28-L30). The documentation can be found [here](https://atom.io/docs/api/v1.2.0/Config).

You would then want to build the path to the rules directory somehow, either have the user specify the entire path and just use that, or let them make it relative to the current file in which case you would need to build the path on the fly. The first is much easier, but I don't know the common practice as to whether that would work better here.

If you have any questions you can ask in the #linter channel on [Atom's Slack](http://atom-slack.herokuapp.com/), or keep commenting here :wink:.

**Comment by buzinas** [comment]
Ok, thanks very much, I'll give a try.

Any idea how to test it?

**Comment by Arcanemagus** [comment]
Not a clue, see my earlier comment about not actually using this linter :stuck_out_tongue:.

**Comment by buzinas** [comment]
Created the pull request https://github.com/AtomLinter/linter-tslint/pull/37.
