### ISSUE TITLE
Question: when releases are made?

### ISSUE THREAD

**Issue by buzinas** [AtomLinter/linter-tslint#38]
Although my issue was closed and my pull request was merged, the current `linter-tslint` package is the same as before. Is there anything wrong or there is some delay between the merge and the next release?

**Comment by buzinas** [comment]
Just saw that you published it as 0.5.0

Thanks very much for your time :)

**Comment by Arcanemagus** [comment]
The delay was I was busy with something else :stuck_out_tongue:
