### ISSUE TITLE
Would you please add a changelog for releases?

### ISSUE THREAD

**Issue by faddah** [AtomLinter/linter-tslint#44]
Would you please be so good as to add a CHANGELOG.md to this repository for each release. Right now, even looking at your code releases, it is impossible to tell what has be added and/or fixed in each release. This would be most helpful. Thank you in advance.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by Arcanemagus** [comment]
A PR adding one would be welcome :wink:.

**Comment by arusakov** [comment]
@faddah I can add descriptions to releases in the [linter-tslint/releases](https://github.com/AtomLinter/linter-tslint/releases). Maybe it is enough?

**Comment by Arcanemagus** [comment]
@arusakov I use https://github.com/skywinder/github-changelog-generator on several of the linters, should be good enough for a start. (If you find a better alternative I'm open to suggestions!)

Atom shows any `CHANGELOG.md` file inside of it, so they are probably looking for that.

**Comment by arusakov** [comment]
CHANGELOG.md added 65480982456d7efbc3bfa6e113f9b94b64cd02b5

**Comment by faddah** [comment]
... thank you!

best,

—  faddah
      portland, oregon, u.s.a.
