### ISSUE TITLE
Support custom rules

### ISSUE THREAD

**Issue by skalidindi** [AtomLinter/linter-tslint#65]
Atom seems to be throwing errors when using custom rules from https://www.npmjs.com/package/ng2lint in tslint.json.

**Comment by arusakov** [comment]
@skalidindi Thank you!
Can you provide some more info (maybe stack trace)? I cannot reproduce error.

**Comment by denis-sokolov** [comment]
My traceback:

```
Error: Could not find the following rules specified in the configuration:
my-custom-rule
    at Object.loadRules (my-project/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (my-project/node_modules/tslint/lib/tslint.js:24:44)
    at ~/.atom/packages/linter-tslint/lib/init.coffee:87:31
```

My rule is added in tslint.json that looks like this:

```json
{
  "rulesDirectory": "custom-tslint-rules",
  "rules": {
    "class-name": true,
    "my-custom-rule": true
  }
}
```

If I run `tslint` on the command line as `tslint`, it respects the `rulesDirectory` and successfully runs my rule.

I run `linter-tslint` 0.8.3, `linter` 1.11.3, Atom 1.7.0-beta0.

**Comment by arusakov** [comment]
@skalidindi @denis-sokolov 
Try to use linter-tslint@0.9.0
