### ISSUE TITLE
TypeError: Linter.findConfigurationPath is not a function at init.coffee:80:38

### ISSUE THREAD

**Issue by ired** [AtomLinter/linter-tslint#68]
In the newest version of the linter there is an error just right after opening a *.ts file.

**Comment by markvandenbrink** [comment]
I've had the same problem and reinstalled linter-tslint (first uninstall, then a fresh new install). That solved the problem for me.

**Comment by ired** [comment]
I had tried this a couple of times and it didn't work (as the reinstalling is the standard procedure in this case), but now it has worked. Thanks

**Comment by Arcanemagus** [comment]
`apm` occasionally has issues properly installing a package, there isn't anything that can really be done about that here though :disappointed:.

**Comment by ired** [comment]
Thanks for your quick help

**Comment by ukaaa** [comment]
I still get the exact same error using the latest version. I tried to reinstall linter-tslint two times but no success.

**Comment by Arcanemagus** [comment]
@ukaaa If you have Node.js installed on your system can you run `npm install` in the package's folder? The only way this should be happening is if it can't get a valid `tslint` install.
