### ISSUE TITLE
TypeError: Linter.findConfigurationPath is not a function

### ISSUE THREAD

**Issue by dawidk92** [AtomLinter/linter-tslint#70]
TypeError: Linter.findConfigurationPath is not a function at [user_path]/.atom/packages/linter-tslint/lib/init.coffee:80:38

Atom: 1.6.0
linter: 1.11.4
linter-tslint: 0.9.0
tslint (npm): 3.5.0
typescript (npm): 1.8.7

**Comment by arusakov** [comment]
Can you uninstall and install linter-tslint again? It has to solve the problem.

**Comment by skalidindi** [comment]
I tried uninstalling and installing again but still get the same issue.
Same versions used as @dawidk92

**Comment by Arcanemagus** [comment]
What does that file look like?

**Comment by skalidindi** [comment]
The error went away after unticking "Try using the local tslint package (if exist)" in the setttings.

**Comment by arusakov** [comment]
@skalidindi 
What version of tslint (in your project package.json) are you use?

**Comment by lordmat0** [comment]
I was having the same problem with 3.2.0-dev.1 but upgraded to 3.6.0 which fixed this issue.

**Comment by arusakov** [comment]
It must be fixed in 0.9.1 version
