### ISSUE TITLE
linter-tslint not able to find custom rules after upgrade to 0.9.0+

### ISSUE THREAD

**Issue by priyatham-aps** [AtomLinter/linter-tslint#72]
I upgraded my linter-tslint from 0.8.3 to 0.9.1 today and since then, linter-tslint is unable to find my custom rules. I have updated the path to absolute path. But it is not working even then.

Following is the error that I am getting:
Could not find the following rules specified in the configuration: ***List of custom rules***

Upgraded the path from `/src/tslint_rules` to `/Users/xxx/xxx/src/tslint_rules`

I also have `useLocalTslint` set to `true`. Locally, I have tslint version 3.6.0-dev.1 running.

Any help is much appreciated.

Thanks.

**Comment by arusakov** [comment]
@priyatham-aps 
Can you provide stack trace and OS, please?

**Comment by priyatham-aps** [comment]
@arusakov 
OS: OSX El Capitan Version 10.11.3

Stacktrace:
Error: Could not find the following rules specified in the configuration:
List of custom rules
    at Object.loadRules (/Users/xxx/xxx/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/xxx/xxx/node_modules/tslint/lib/tslint.js:24:44)
    at /Users/xxx/.atom/packages/linter-tslint/lib/init.coffee:99:31

**Comment by cadriel** [comment]
We have the same issue. Latest update has broken external rules. tslint from the command line works. Also on osx.

```
Error: Could not find custom rule directory: /node_modules/codelyzer/dist/src
Error: Could not find custom rule directory: /node_modules/codelyzer/dist/src
    at Object.getRulesDirectories (/Users/xxx/node_modules/tslint/lib/configuration.js:163:19)
    at findRule (/Users/xxx/node_modules/tslint/lib/ruleLoader.js:42:39)
    at Object.loadRules (/Users/xxx/node_modules/tslint/lib/ruleLoader.js:14:24)
    at Linter.lint (/Users/xxx/node_modules/tslint/lib/tslint.js:26:44)
    at /Users/xxx/.dotfiles/atom/atom.symlink/packages/linter-tslint/lib/init.coffee:99:31```

**Comment by d3viant0ne** [comment]
Same here and same error
