### ISSUE TITLE
Error: Could not find the following rules specified in the configuration: no-angle-bracket-type-assertion

### ISSUE THREAD

**Issue by dcsan** [AtomLinter/linter-tslint#87]
this error suddenly started happening to me today.

![image](https://cloud.githubusercontent.com/assets/514002/15093528/93f4d97a-14bd-11e6-8af6-95d440204263.png)

changing the rule to false has no effect

    "no-angle-bracket-type-assertion": false,

removing the rule makes the linter go crazy!!

![image](https://cloud.githubusercontent.com/assets/514002/15093535/cd41cd28-14bd-11e6-8b50-3aaabf4d3d22.png)

so I:m not really sure how to get around this...

**Comment by dcsan** [comment]
I'm using 

tslint 0.9.1
atom-typescript 8.3.0

**Comment by Arcanemagus** [comment]
That rule [first appeared](https://github.com/palantir/tslint/commit/86611852fc2b8bfb9534a2ab61f565ac22d3a7eb) in `tslint@3.7.0-dev.1`. `linter-tslint` v0.9.1 only includes `tslint@3.6.0`.

If you update to the latest version you will be updated to `tslint@3.8.1` and it should then know about that rule.

**Comment by dcsan** [comment]
thanks for update - so i need to ask linter-tslint guys to update to use a later version of tslint ?

**Comment by Arcanemagus** [comment]
No.... you need to update to the latest version of `linter-tslint`. Like I said the latest version should understand that rule.
