### ISSUE TITLE
Performance issues with multiple rules

### ISSUE THREAD

**Issue by Fank** [AtomLinter/linter-tslint#93]
If i write something i get a 1-2 sec lag.

Here is the timeline for reference it happens if i stop writing, and start writing again.
![screenshot from 2016-05-24 14-47-46](https://cloud.githubusercontent.com/assets/1900106/15504275/8197eeee-21be-11e6-8b53-ccba106652d0.png)

It looks like the process is syncron with atom, and tslint will take a little bit to complete the linting, so in this time atom freezes.

**Comment by Arcanemagus** [comment]
The way to solve this is to move running `tslint` to a separate process, if you want to take a stab at it the only linter plugin that currently works in that manner is https://github.com/AtomLinter/linter-eslint.

**Comment by Fank** [comment]
Related performance issue in tslint https://github.com/AtomLinter/linter-tslint/issues/93

**Comment by beckend** [comment]
I was gonna hack this plugin but I'm not a coffee script person, so I took bit a pieces from `linter-eslint` and this plugin and wrote the same thing with web worker like `linter-eslint` in es6/es7.

I also fixed #109 and included type checking program in tslint.
There are some basic specs, but I'm not planning to maintain it. You are welcome take whatever you want.

[tslint2 unofficial](https://github.com/beckend/linter-tslint2).

At least it does not lag anymore, just a shame that I cannot figure out how to tell typescript to lint the new content so on the fly lint works.

**Comment by Arcanemagus** [comment]
@beckend Any reason you didn't just make a PR? 😛

**Comment by beckend** [comment]
I have no excuse for that, I guess I'm just really stressed to have stuff finished at work.

**Comment by Arcanemagus** [comment]
No worries lol, if you want to make a PR at some point and get credit for your work feel free 😉.

**Comment by Xapphire13** [comment]
`linter-tslint` now uses async workers as of [#158](https://github.com/AtomLinter/linter-tslint/pull/158)
