### ISSUE TITLE
Could not find the following rules specified in the configuration

### ISSUE THREAD

**Issue by aroder** [AtomLinter/linter-tslint#94]
Hi, I get this error from atom:

```
Error: Could not find the following rules specified in the configuration: new-parens no-default-export one-variable-per-declaration
Error: Could not find the following rules specified in the configuration:
new-parens
no-default-export
one-variable-per-declaration
    at Object.loadRules (/Users/adam/.atom/packages/linter-tslint/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/adam/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:26:44)
    at /Users/adam/.atom/packages/linter-tslint/lib/init.coffee:101:31
```

No error from command line running tslint -c tslint.json src/app/settings.ts 

tslint -v shows 2.10.2
atom version of linter-tslint shows 0.9.3
atom version of linter shows 1.11.4

I checked the latest [tslint rules ](https://palantir.github.io/tslint/rules/) and the three rules in the error are valid rule names.

Any ideas what else I can check?

**Comment by Arcanemagus** [comment]
`tslint` has [never released](https://github.com/palantir/tslint/releases) a 2.10.2 version so... I'm not sure _what_ you are running?

This package integrates the 3.8.1 version of `tslint` in the currently released version, can you try again with that version or later?

**Comment by Arcanemagus** [comment]
Ah ha! Assuming you meant `tslint` **3**.10.2, then you are trying to use rules that didn't exist yet till that version. I'm releasing an update to this package shortly that includes that version which should fix your issue.

**Comment by Arcanemagus** [comment]
`linter-tslint` v0.10.0 should fix this for you. :tada:

**Comment by aroder** [comment]
Thanks, Landon! Yes, I mean 3.10.2



Adam Roderick
aroder@gmail.com
