### ISSUE TITLE
Linter.findConfigurationPath is not a function on 0.10.0

### ISSUE THREAD

**Issue by chuanxie** [AtomLinter/linter-tslint#95]
it happens again.
TypeError: Linter.findConfigurationPath is not a function
    at /Users/name/.atom/packages/linter-tslint/lib/init.coffee

**Comment by Arcanemagus** [comment]
Can you place a breakpoint [here](https://github.com/AtomLinter/linter-tslint/blob/v0.10.0/lib/init.coffee#L80), trigger a lint, and see what `Linter` contains?

It sounds like it _thinks_ it's finding a `tslint` install in your project, but whatever it's finding doesn't have the proper functions.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
